<?php

/*
 * -------------------------------------------------------------
 * N.B: Page Type Declare Rule
 * -------------------------------------------------------------
 * For Page Type Also add page type in frontend.php in
 * /plugins/Frontend/Config/frontend.php file
 */

return [
    'default' => env('DEFAULT_TEMPLATE', 'template-1'),
    'logo_path' => 'https://mountainwest.s3.amazonaws.com/images/banners/car-audio-banner-full.jpeg',
    'favicon_path' => 'https://mountainwest.s3.amazonaws.com/images/banners/car-audio-banner-full.jpeg',
    'email' => null,
    'phone' => null,
    'header_content' => null,
    'slogan' => '"Working together to make America safe"',
    'favicon' => '',
    'fallback' => 'demo',
    'page_types' => [
        [
            'code' => 'home',
            'label' => 'Home',
            'description' => 'Test',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'shop',
            'label' => 'Shop',
            'description' => 'Shop Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.shop.index',
                'params' => 'home',
            ],
        ],
        [
            'code' => 'single_product',
            'label' => 'Single Product',
            'description' => 'Single Product Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.shop.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'cart',
            'label' => 'Cart Page',
            'description' => 'Cart Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.carts.index',
                'params' => '', ],
        ],
        [
            'code' => 'shop_category',
            'label' => 'Shop Category',
            'description' => 'Shop Category Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.categories',
                'params' => '',
            ],
        ],
        [
            'code' => 'quick_order',
            'label' => 'Quick Order',
            'description' => 'Quick Order Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'slug',
                'name' => null,
                'params' => '',
            ],
        ],
        [
            'code' => 'checkout',
            'label' => 'Cart Checkout',
            'description' => 'Cart Checkout Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.checkout',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_checkout_confirm',
            'label' => 'Order Checkout Confirm',
            'description' => 'Order Checkout Confirm Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order.checkout',
                'params' => '',
            ],
        ],
        [
            'code' => 'order',
            'label' => 'Order',
            'description' => 'Order Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.orders.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_completed',
            'label' => 'Order Completed',
            'description' => 'Order Completed Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.orders.completed',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_detail',
            'label' => 'Order Details',
            'description' => 'Order Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.orders.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'draft_order',
            'label' => 'Draft Order',
            'description' => 'Draft Order Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.drafts.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'draft_order_detail',
            'label' => 'Draft Order Details',
            'description' => 'Draft Order Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.drafts.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'quotation',
            'label' => 'Quotation',
            'description' => 'Quotation Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.quotations.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'quotation_detail',
            'label' => 'Quotation Details',
            'description' => 'Quotation Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.quotations.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'favourite',
            'label' => 'Favourite List',
            'description' => 'Favourite List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.favourites.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'favourite_detail',
            'label' => 'Favourite List Details',
            'description' => 'Favourite List Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.favourites.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'favourite_edit',
            'label' => 'Favourite List Edit',
            'description' => 'Favourite List Edit Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.favourites.edit',
                'params' => '',
            ],
        ],
        [
            'code' => 'quicklist',
            'label' => 'Quick List',
            'description' => 'Quick List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.quick-lists.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'quicklist_detail',
            'label' => 'Quick List Details',
            'description' => 'Quick List Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.quick-lists.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'quicklist_create',
            'label' => 'Quick List Create',
            'description' => 'Quick List Update Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.quick-lists.create',
                'params' => '',
            ],
        ],
        [
            'code' => 'quicklist_edit',
            'label' => 'Quick List Update',
            'description' => 'Quick List Update Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.quick-lists.edit',
                'params' => '',
            ],
        ],
        [
            'code' => 'static_page',
            'label' => 'Static',
            'description' => 'Static Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'slug',
                'name' => null,
                'params' => '',
            ],
        ],
        [
            'code' => 'dashboard',
            'label' => 'Dashboard',
            'description' => 'Dashboard Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.dashboard',
                'params' => '',
            ],
        ],
        [
            'code' => 'message',
            'label' => 'Message',
            'description' => 'Message Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.messages.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'message_detail',
            'label' => 'Message',
            'description' => 'Message Detail',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.messages.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'payment',
            'label' => 'Payment',
            'description' => 'Payment Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'slug',
                'name' => null,
                'params' => '',
            ],
        ],
        [
            'code' => 'login',
            'label' => 'Login',
            'description' => 'Login Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.login',
                'params' => '', ],
        ],
        [
            'code' => 'registration',
            'label' => 'Registration',
            'description' => 'Registration Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.registration',
                'params' => '',
            ],
        ],
        [
            'code' => 'forgot_password',
            'label' => 'Forgot Password',
            'description' => 'Forgot Password Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.password.request',
                'params' => '',
            ],
        ],
        [
            'code' => 'force_password_reset',
            'label' => 'Forgot Password',
            'description' => 'Forgot Password Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.force-reset-password',
                'params' => '',
            ],
        ],
        [
            'code' => 'password_reset',
            'label' => 'Password Reset',
            'description' => 'Password Reset Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.password.reset',
                'params' => '', ],
        ],
        [
            'code' => 'invoice',
            'label' => 'Invoice List',
            'description' => 'Invoice Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.invoices.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'invoice_detail',
            'label' => 'Invoice Details',
            'description' => 'Invoice Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.invoices.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'ticket',
            'label' => 'Tickets List',
            'description' => 'Tickets List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.tickets.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'ticket_open',
            'label' => 'Open Ticket',
            'description' => 'Open Ticket Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.tickets.create',
                'params' => '',
            ],
        ],
        [
            'code' => 'ticket_detail',
            'label' => 'Ticket Details',
            'description' => 'Ticket Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.tickets.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'customer_profile',
            'label' => 'My Profile',
            'description' => 'Authenticated contact\'s profile setting',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.profile.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'switch_account',
            'label' => 'Switch Account',
            'description' => 'Switch account setting',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.switch-account.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'contact',
            'label' => 'Contacts List',
            'description' => 'Contacts List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.contacts.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'contact_create',
            'label' => 'Contact Create',
            'description' => 'Contacts Create Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.contacts.create',
                'params' => '',
            ],
        ],
        [
            'code' => 'contact_edit',
            'label' => 'Contact Edit',
            'description' => 'Contacts Edit Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.contacts.edit',
                'params' => '',
            ],
        ],
        [
            'code' => 'contact_detail',
            'label' => 'Contact Details',
            'description' => 'Contact Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.contacts.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'role',
            'label' => 'Role List',
            'description' => 'Role List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.roles.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'role_create',
            'label' => 'Create Role',
            'description' => 'Role Create Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.roles.create',
                'params' => '',
            ],
        ],
        [
            'code' => 'role_edit',
            'label' => 'Edit Role',
            'description' => 'Role Edit Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.roles.edit',
                'params' => '',
            ],
        ],
        [
            'code' => 'role_detail',
            'label' => 'Role Details',
            'description' => 'Role Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.roles.show',
                'params' => '',

            ],
        ],
        [
            'code' => 'address',
            'label' => 'Address List',
            'description' => 'Address List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.addresses.index',
                'params' => '', ],
        ],
        [
            'code' => 'address_create',
            'label' => 'Create Address',
            'description' => 'Address Create Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.addresses.create',
                'params' => '',
            ],
        ],
        [
            'code' => 'address_edit',
            'label' => 'Edit Address',
            'description' => 'Address Edit Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.addresses.edit',
                'params' => '',
            ],
        ],
        [
            'code' => 'address_details',
            'label' => 'Address Details',
            'description' => 'Address Details Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.addresses.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'account_summary',
            'label' => 'Account Summary',
            'description' => 'Account Summary Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.account-summary',
                'params' => '',
            ],
        ],
        [
            'code' => 'shop_brand',
            'label' => 'Shop Brand Page',
            'description' => 'Shop Brand Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.brands',
                'params' => '',
            ],
        ],
        [
            'code' => 'campaign',
            'label' => 'Campaign List',
            'description' => 'Campaign List',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.campaigns.index',
                'params' => '', ],
        ],
        [
            'code' => 'campaign_details',
            'label' => 'Campaign Details',
            'description' => 'Campaign Details',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.campaigns.show',
                'params' => '', ],
        ],
        [
            'code' => 'order_rule',
            'label' => 'Order Rule List',
            'description' => 'Order Rule Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-rules.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_rule_create',
            'label' => 'Order Rule Create',
            'description' => 'Order Rule Create Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-rules.create',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_rule_edit',
            'label' => 'Order Rule Edit',
            'description' => 'Order Rule Edit Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-rules.edit',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_awaiting_approval',
            'label' => 'Order Awaiting Approval List',
            'description' => 'Order Awaiting Approval List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-awaiting-approvals.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_awaiting_approval_detail',
            'label' => 'Order Awaiting Approval Detail',
            'description' => 'Order Awaiting Approval Detail Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-awaiting-approvals.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_approval',
            'label' => 'Order Approval List',
            'description' => 'Order Approval List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-approvals.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_approval_detail',
            'label' => 'Order Approval Detail',
            'description' => 'Order Approval Detail Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-approvals.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_rejected',
            'label' => 'Order Reject List',
            'description' => 'Order Reject List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-rejects.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_reject_detail',
            'label' => 'Order Reject Detail',
            'description' => 'Order Reject Detail Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-rejects.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'past_items',
            'label' => 'Past Items',
            'description' => 'Past Items Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.past.items',
                'params' => '',
            ],
        ],
        [
            'code' => 'contact_login',
            'label' => 'Login Manager List',
            'description' => 'Login Manager List Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.contact-logins.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'contact_login_edit',
            'label' => 'Login Manager Edit',
            'description' => 'Contact Login Manager Role Permission Update Page',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.contact-logins.edit',
                'params' => '',
            ],
        ],
        [
            'code' => 'event',
            'label' => 'Event List',
            'description' => 'Event List',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.events.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'event_details',
            'label' => 'Event Details',
            'description' => 'Event Details',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.events.show',
                'params' => '',
            ],
        ],
        [
            'code' => 'order_status',
            'label' => 'Order Status',
            'description' => 'Order Status',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.order-status',
                'params' => '',
            ],
        ],

        [
            'code' => 'custom_product',
            'label' => 'Custom Product',
            'description' => 'Custom Product',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'custom.product',
                'params' => '',
            ],
        ],

        [
            'code' => 'invoice_pay',
            'label' => 'Invoice Cenpos Pay',
            'description' => 'Invoice Cenpos Pay',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'customer.cenpos-invoices-pay.index',
                'params' => '',
            ],
        ],
        [
            'code' => 'shipping_address',
            'label' => 'Shipping Address',
            'description' => 'Force select shipping address after login',
            'middleware' => ['customers'],
            'reserved' => true,
            'url' => [
                'type' => 'slug',
                'name' => '',
                'params' => '',
            ],
        ],
        [
            'code' => 'content_detail',
            'label' => 'Content Preview',
            'description' => 'Content Full Preview Page',
            'middleware' => [],
            'reserved' => true,
            'url' => [
                'type' => 'route',
                'name' => 'frontend.contents.show',
                'params' => 'demo',
            ],
        ],
    ],
    'themes' => [
        'demo' => [
            'id' => 1,
            'label' => 'Amplify Demo',
            'slug' => 'demo',
            'component_folder' => 'demo',
            'asset_folder' => 'demo',
            'description' => 'Amplify Demo',
        ],
    ],
    'middleware' => [
        'default' => 'guest',
        'middlewares' => [
            'guest' => [
                'guard' => 'guest',
                'label' => 'Public',
                'description' => 'Everyone can see page content.',
            ],
            /*            'guest:customer' => [
                'guard' => 'guest:customer',
                'label' => 'Guest',
                'description' => 'Only available if customer is not logged in.',
            ],*/
            'customers' => [
                'guard' => 'customers',
                'label' => 'Authenticated',
                'description' => 'Only logged in person can see page content.',
            ],
        ],
    ],
];
